module Database.Migrate.Main where

usage :: [String]
usage = [
    "usage: db migrate  [OPTIONS] [MIGRATION]"
  , "       db up       [OPTIONS] MIGRATION ..."
  , "       db down     [OPTIONS] MIGRATION ..."
  , "       db fix-up   [OPTIONS] MIGRATION"
  , "       db fix-down [OPTIONS] MIGRATION"
  , "       db history  [OPTIONS]"
  , "       db status   [OPTIONS]"
  , "       db generate [OPTIONS]"
  , "       db reset    [OPTIONS]"
  , "       db seed     [OPTIONS] DATASET ..."
  , "       db baseline [OPTIONS]"
  , "       db -h|--help"
  , "       db -V|--version"
  , ""
  , "STANDARD OPTIONS"
  , "----------------"
  , ""
  , "These options are supported by all commands."
  , ""
  , "  -v|--verbose          Enable verbose output, commands are quiet be default."
  , "  -d|--dry-run          Prevents any destructive updates from being run, this"
  , "                        option implies `--verbose` so the run behaviour can"
  , "                        examined. Non-destructive commands will behave normally."
  , "  -e|--environment ENV  Specifies a pre-configured environment to run against,"
  , "                        this is ignored if `--connection` is specified."
  , "  -c|--connection CONN  A connection string for a database to run against, this"
  , "                        overrides any `--environment` setting."
  , "  -m|--migrations DIR   Specify a base directory for migration files."
  , "  -y|--yes              Accept defaults for any interactive options, this is"
  , "                        useful for running commands in scripts."
  , ""
  , "COMMANDS"
  , "--------"
  , ""
  , "  migrate [MIGRATION]   Migrate to latest, or specific version if specified. This"
  , "                        command will determine all unapplied migrations and run"
  , "                        the appropriate up/down commands."
  , "  up MIGRATION ...      Run up change for specific migrations."
  , "  down MIGRATION ...    Run down change for specific migrations."
  , "  fix-up MIGRATION      Fix migration meta-data by recording MIGRATION up."
  , "  fix-down MIGRATION    Fix migration meta-data by recording MIGRATION down."
  , "  history               Display migration history."
  , "  status                Display current database status, i.e. what migrations are applied vs not."
  , "  generate              Generate change files."
  , "  test                  Runs all up's then all down's on database."
  , "  reset                 Runs all up's then all down's on database."
  , "  seed DATASET ...      Seed database with datasets."
  , "  baseline              Perform a schema dump to baseline the current database."
  , ""
  ]
